### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by dadoonet** [elastic/beat-generator#25]
In source file we are currently using `tab` and not `spaces` for the code.

In elasticsearch project we prefer using spaces. Is it a common thing to use tabs in Go? Or could we change the generator to use tabs instead?

**Comment by andrewkroh** [comment]
Check out [Effective Go - Formatting](https://golang.org/doc/effective_go.html#formatting). Tabs are the standard and there's a tool, `gofmt`, to apply the standard formatting to Go source files.

**Comment by dadoonet** [comment]
Thanks! Closing then!
