### ISSUE TITLE
Xgo not found when running the make step in a beat-generator generated beat

### ISSUE THREAD

**Issue by jerrac** [elastic/beat-generator#30]
After making a test beat with [beat-generator](https://github.com/elastic/beat-generator), I tried building it with the dev-tools/packer scripts.

The readme has this section:

> ### Package

> To cross-compile and package Davidbeat for all supported platforms, run the following commands:

> ```
> cd dev-tools/packer
> make deps
> make images
> make
> ```

I successfully ran the first three commands. (Though ```make images``` had to be run a few times when my system couldn't connect to archive.debian.org for a while...) But when I run ```make```, it throws an error.

```
$GOPATH/path/to/packer: make
mkdir -p build/upload
# cross compile on ubuntu
cd build && xgo -image=tudorg/beats-builder \
        -before-build=../../../vendor/github.com/elastic/beats/dev-tools/packer/xgo-scripts/before_build.sh \
        -pkg davidbeat \
        -source ../../.. \
        github.com/jerrac/davidbeat
/bin/sh: 1: xgo: not found
make: *** [davidbeat] Error 127

```

Did ```make deps``` not install xgo? Was it supposed to? Or was I supposed to manually install?

I'm running LinuxMint 17.2. Which is basically the same as Ubuntu 14.04 from what I can tell. 64bit.

**Comment by ruflin** [comment]
@jerrac Thanks for reporting. Can you check if it works when you install xgo from here: https://github.com/tsg/xgo ?

**Comment by tsg** [comment]
I suspect the issue is that you don't have `$GOPATH/bin` in your `$PATH`. Try seeing if `$GOPATH/bin/xgo` exists, and if yes, add that to your `PATH`.

**Comment by jerrac** [comment]
Hmm... The path issue was the problem.  And here I thought I had set up my path correctly... 

Thanks @tsg !

If you ever add a troubleshooting section somewhere, mentioning that you PATH needs to be setup correctly would be a good thing to add. :)

**Comment by ruflin** [comment]
@jerrac Good to hear it works now. Probably it would be best to add a note to this README here: https://github.com/elastic/beats/tree/master/dev-tools/packer
