### ISSUE TITLE
Improve Dependency Management

### ISSUE THREAD

**Issue by ruflin** [elastic/beat-generator#4]
Currently beat-generator requires `glide init` and `glide update` to be run after creation to fetch the dependencies. Because of all beat dependencies in the top vendor directory, glide seems to fetch unrequired dependencies, from example `labix.org/v2/mgo/bson`. This leads to issues as labix requires bazaar and makes the dependencies larger then needed. There are different solutions here:

* Check in glide.lock file and have it as part of the generator
* Make vendor directory as part of the generator. Advantage is that to run a beat no glide is required

**Comment by ruflin** [comment]
@cyrilleverrier Perhaps you have some more ideas on how to tackle the above problem? As a side note: Just discovered this command: https://github.com/Masterminds/glide#glide-novendor-aliased-to-nv

**Comment by cyrilleverrier** [comment]
I prefer to run  `glide update --no-recursive` in order to not fetch libbeat's dependencies.
They are already in libbeat/vendor folder anyway.

From help page:

```
	If a dependency has a glide.yaml file, update will read that file and
	update those dependencies accordingly. Those dependencies are maintained in
	a the top level 'vendor/' directory. 'vendor/foo/bar' will have its
	dependencies stored in 'vendor/'. This behavior can be disabled with
	'--no-recursive'. When this behavior is skipped a glide.lock file is not
	generated because the full dependency tree cannot be known.


   --no-recursive, --quick	Disable updating dependencies' dependencies. Only update things in glide.yaml.
```

**Comment by ruflin** [comment]
@cyrilleverrier Thanks for the help. That works. It didn't work previously because of a typo on my side :-(

Seems like we need to make this line also variable based: https://github.com/elastic/beats/blob/master/libbeat/scripts/Makefile#L198

**Comment by ruflin** [comment]
Closing as this was resolved-
